### PR TITLE
18.12 RC1 Merge #3

### PR DESCRIPTION
**Pull request by sjsadowski**
Merging changes from master in to 18.12 branch for (hopefully) the last time.

### CODE REVIEW

**Comment by ahopkins** [comment]
Wow. Look at all that green! Excellent work to everyone who contributed to this.

**Comment by yunstanford** [comment]
it requires update branch, not able to merge in..

**Comment by yunstanford** [comment]
Anyway, i'll update version and attach tag on master, since we have to do it anyway.

**Comment by ahopkins** [comment]
> And we probably don't need a separate branch for tracking release version, since github will take snapshots when attaching tags.

@yunstanford Except 18.12 is LTS, meaning we will still want to release bug fixes on this while master diverges with new features, etc.

**Comment by ahopkins** [comment]
FYI - Travis is building because of this:

```The command "eval git clone --depth=50 --branch=v18.12.0 https://github.com/huge-success/sanic.git huge-success/sanic " failed. Retrying, 2 of 3.```

**Comment by ahopkins** [comment]
I am closing this branch in favor of the 18.12LTS branch.

**Comment by ahopkins** [comment]
I think this is a better practice. No need to do these branches before master is ready and released.

**Pull request closed without merging**
