### PR TITLE
Codestyle black

### PR DESCRIPTION
**Pull request by yunstanford**
Start a conversation around adopting `black` for code style. This PR includes,

1. Run black against `sanic` module
2. Added black check in tox, `black --check --verbose sanic`

### CODE REVIEW

**Comment by ahopkins** [comment]
I am in favor of "uncompromising" consistency.

**Comment by vltr** [comment]
@yunstanford can't we add some more rules regarding `isort` and `flake8`, as mentioned by the [black documentation](https://github.com/ambv/black#the-black-code-style) itself? Also, I started a forum discussion [regarding this](https://community.sanicframework.org/t/python-and-documentation-code-rules/38/3) some days ago, it might worth looking as well.

**Comment by yunstanford** [comment]
@vltr will take a look, thanks!

**Comment by vltr** [comment]
Thanks, @yunstanford !

**Comment by yunstanford** [comment]
@vltr i'm fine with `isort`, does it provide any check command like `black` ? or just always run isort against the repo ?

And also why do we want to ignore `C901` ?

**Comment by vltr** [comment]
Oh, `C901` I think is residual from my old days with Twisted, just ignore it (in the forums I put just a sample, not a solution for Sanic).

As for `isort`, it plays well with some editors, as `black` respects its rules. It can also be used as a command line check, exactly like `black`. Here's the command line I use inside my `tox.ini` files:

```
    isort --verbose --check-only --diff --recursive src tests setup.py
```

**Pull request merged**
