### PR TITLE
fixbug: IndexError in request.Request.remote_addr

### PR DESCRIPTION
**Pull request by PWZER**
FixBug

```python
# from request.py:383

remote_addrs = [
    addr
    for addr in [addr.strip() for addr in forwarded_for]
    if addr
]
if self.app.config.PROXIES_COUNT == -1:
    self._remote_addr = remote_addrs[0]  # IndexError: list index out of range
```

### CODE REVIEW

**Comment by ahopkins** [comment]
Thanks for the PR. Can you explain the bug this is resolving?

**Comment by andreymal** [comment]
Oh shame, I forgot this obvious test >_<

<details>
<summary>Click me</summary>

```diff
diff --git a/tests/test_requests.py b/tests/test_requests.py
index ea1946d..a01b53c 100644
--- a/tests/test_requests.py
+++ b/tests/test_requests.py
@@ -408,6 +408,11 @@ def test_remote_addr_with_two_proxies(app):
     async def handler(request):
         return text(request.remote_addr)
 
+    headers = {}
+    request, response = app.test_client.get("/", headers=headers)
+    assert request.remote_addr == ""
+    assert response.text == ""
+
     headers = {"X-Real-IP": "127.0.0.2", "X-Forwarded-For": "127.0.1.1"}
     request, response = app.test_client.get("/", headers=headers)
     assert request.remote_addr == "127.0.0.2"
@@ -448,6 +453,11 @@ async def test_remote_addr_with_two_proxies_asgi(app):
     async def handler(request):
         return text(request.remote_addr)
 
+    headers = {}
+    request, response = await app.asgi_client.get("/", headers=headers)
+    assert request.remote_addr == ""
+    assert response.text == ""
+
     headers = {"X-Real-IP": "127.0.0.2", "X-Forwarded-For": "127.0.1.1"}
     request, response = await app.asgi_client.get("/", headers=headers)
     assert request.remote_addr == "127.0.0.2"
@@ -487,6 +497,11 @@ def test_remote_addr_with_infinite_number_of_proxies(app):
     async def handler(request):
         return text(request.remote_addr)
 
+    headers = {}
+    request, response = app.test_client.get("/", headers=headers)
+    assert request.remote_addr == ""
+    assert response.text == ""
+
     headers = {"X-Real-IP": "127.0.0.2", "X-Forwarded-For": "127.0.1.1"}
     request, response = app.test_client.get("/", headers=headers)
     assert request.remote_addr == "127.0.0.2"
@@ -513,6 +528,11 @@ async def test_remote_addr_with_infinite_number_of_proxies_asgi(app):
     async def handler(request):
         return text(request.remote_addr)
 
+    headers = {}
+    request, response = await app.asgi_client.get("/", headers=headers)
+    assert request.remote_addr == ""
+    assert response.text == ""
+
     headers = {"X-Real-IP": "127.0.0.2", "X-Forwarded-For": "127.0.1.1"}
     request, response = await app.asgi_client.get("/", headers=headers)
     assert request.remote_addr == "127.0.0.2"
@@ -538,6 +558,11 @@ def test_remote_addr_without_proxy(app):
     async def handler(request):
         return text(request.remote_addr)
 
+    headers = {}
+    request, response = app.test_client.get("/", headers=headers)
+    assert request.remote_addr == ""
+    assert response.text == ""
+
     headers = {"X-Real-IP": "127.0.0.2", "X-Forwarded-For": "127.0.1.1"}
     request, response = app.test_client.get("/", headers=headers)
     assert request.remote_addr == ""
```

</details>

**Comment by andreymal** [comment]
@PWZER [ping?](https://github.com/huge-success/sanic/pull/1615#issuecomment-506238487)

**Comment by PWZER** [comment]
@ahopkins @andreymal 

This bug is a logical problem in the code, before using `remote_addrs[0]` did not judge whether `remote_addrs` is zero-length, so get IndexError.

https://github.com/huge-success/sanic/blob/84b41123f29e8f52c63c82af6f9279a6edaaf1a0/sanic/request.py#L415-L421

The following is my modification

```diff
-                if self.app.config.PROXIES_COUNT == -1:
+                if len(remote_addrs) == 0:
+                    self._remote_addr = ""
+                elif self.app.config.PROXIES_COUNT == -1:
```

**Comment by Tronic** [comment]
The fix seems valid. Do note that pull request #1638 also re-implements this code, avoiding the problem.

**Comment by arcana261** [comment]
@PWZER why did you close this? :'(  #1638 is still work in progress as of now!

**Pull request closed without merging**
