### PR TITLE
fix packaging module do not have version attribute

### PR DESCRIPTION
**Pull request by hanleilei**
I tried to run pytest in sanic folder, but got this:

`pytest                          ✔  2071  21:15:18
================================================= test session starts =================================================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/hanlei/Documents/python/sanic, inifile:
plugins: remotedata-0.2.1, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2, celery-4.1.0
collected 363 items / 1 errors

======================================================= ERRORS ========================================================
___________________________________ ERROR collecting tests/test_request_timeout.py ____________________________________
tests/test_request_timeout.py:21: in <module>
    version = packaging.version
E   AttributeError: module 'packaging' has no attribute 'version'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 1 error in 0.59 seconds ===============================================
`

I found that the packaging module does not have the version attribute.

we can edit the packaging/__init__.py, just add

`import packing.version`

can fix this problem too. but that's another problem.

### CODE REVIEW

**Comment by sjsadowski** [comment]
Can you update your fork to the current master and then we can make sure the tests pass and get this reviewed.

**Comment by yunstanford** [comment]
Actually, I'd like to refactor this unit test, https://github.com/huge-success/sanic/blob/master/tests/test_keep_alive_timeout.py#L33, it'd remove a lot of nasty-ness.

It's actually a little weird to handle different versions of `aiohttp` that way in unit tests.

**Comment by hanleilei** [comment]
thanks, @yunstanford, I raise this pull request due to finding the unit test is broken: 

AttributeError: module 'packaging' has no attribute 'version'

the packing module does not have the version as its attribute. so I removed the import packaging statement.

**Comment by sjsadowski** [comment]
@hanleilei Hey there - can you update your branch again? Thanks!

**Comment by sjsadowski** [comment]
I'm closing this PR, I can't duplicate on current master.

**Pull request closed without merging**
