### PR TITLE
Deprecate body_bytes to merge into body

### PR DESCRIPTION
**Pull request by LiraNuna**
As suggested in https://github.com/huge-success/sanic/pull/1736#issuecomment-568266049, this PR deprecates `body_bytes` and merges it into `body`.

Please note that I have intentionally removed the `body_bytes` param completely to elicit discussion about how to properly deprecate it (cc @ahopkins who has some thoughts to share).

### CODE REVIEW

**Comment by Tronic** [comment]
Check out #1674 as there is some overlap, in particular with how bytes vs. other types are detected.

**Comment by LiraNuna** [comment]
Sure, I can upgrade body to bytes but that will keep the weirdness that is the two parameters merging into the same thing. 

Here are the questions I have in a more blunt form:
* How will the developer know to stop using `body_bytes` and to start using `body`?
* When will `body_bytes` be removed?
* What happens if both `body` and `body_bytes` are passed in?
* And what's up with `black` adding comma to line 208?

**Comment by LiraNuna** [comment]
@Tronic, my main questions are "is it okay to deprecate this parameter?" and "how will library users know to avoid code breakage?"

I'm assuming a version bump and a note in the CHANGELOG, but is it this PR's responsibility to do that? 

I think this PR is ready to review assuming the param deprecation is wanted.

**Comment by ahopkins** [comment]
Sorry for not jumping in with thoughts sooner. I was sort of waiting for [the new organizational structure](https://sanicframework.org/2020-release-managers-and-a-new-oraganizational-structure) to kick in and let there be a bit more of a formalized discussion about how to handle deprecations.

I would like to put this one on hold until that conversation takes place. I expect the Steering Council to be in place within the next week or two.

**Comment by Tronic** [comment]
@ahopkins Any updates on that? I'd like to see this merged for 20.3.

**Comment by LiraNuna** [comment]
What is stopping this PR from being merged? I'd love to get it over the finish line

**Comment by Tronic** [comment]
Alternatively, modify this PR so that it still takes body_bytes arguments but gives a warning whenever those are used.

**Comment by LiraNuna** [comment]
@Tronic how does this look? I chose to accept the old param so when the true deprecation comes, there are more options

**Pull request merged**
