### PR TITLE
Bug fix for host parameter issue with lists

### PR DESCRIPTION
**Pull request by damianj**
As explained in #1772 there is an issue when using a list as an argument for the host parameter in the Blueprint.route() decorator. I've traced the issue back to this line, and the if conditional should ensure that the name attribute isn't accessed when route is None.

### CODE REVIEW

**Comment by damianj** [comment]
@ahopkins I think the tests are being addressed in #1775? Unless that is not addressing Blueprint.route() tests.

**Comment by damianj** [comment]
@ahopkins I added some unit tests for using lists with the host parameter. There were already some for testing strings with the host parameter.

**Comment by sjsadowski** [comment]
@ahopkins can you resolve your change request if you think that we've met your threshhold?

**Comment by damianj** [comment]
Just following up to see if there is anything else I can or need to do in order to get this merged?

**Comment by Tronic** [comment]
> This seems like an okay change. But, it might be nice to have a test with host routing with a string and a list of strings.
> 
> Thanks for the PR.

#1775 was closed (stale) and this now has tests. Can we resolve this change request and get this merged?

**Pull request merged**
