### PR TITLE
Fix static _handler pickling error.

### LINKED ISSUE #1774: `AttributeError: Can't pickle local object 'register.<locals>._handler'` sanic 19.12.2; python3.8.2; sanic-cors==0.10.0.b1
Hi.

On OSX 10.14.6, python 3.8.1

    conda list sanic                                                                                                
    # packages in environment at /Users/efarrell/miniconda3/envs/LG-py38:
    #
    # Name                    Version                   Build  Channel
    pytest-sanic              1.1.2                    pypi_0    pypi
    sanic                     19.12.2                  py38_0    conda-forge
    sanic-cors                0.10.0b1                 pypi_0    pypi
    sanic-openapi3e           0.6.2                    pypi_0    pypi
    sanic-plugins-framework   0.9.0b1                  pypi_0    pypi

I cannot start an API due to 

    Traceback (most recent call last):
      File "API/src/main.py", line 613, in <module>
        main(sys.argv)
      File "API/src/main.py", line 195, in main
        app.go_fast(**sanic_run_env)
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/site-packages/sanic/app.py", line 1169, in run
        serve_multiple(server_settings, workers)
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/site-packages/sanic/server.py", line 997, in serve_multiple
        process.start()
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/multiprocessing/process.py", line 121, in start
        self._popen = self._Popen(self)
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
        return _default_context.get_context().Process._Popen(process_obj)
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
        return Popen(process_obj)
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
        super().__init__(process_obj)
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
        self._launch(process_obj)
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
        reduction.dump(process_obj, fp)
      File "/Users/efarrell/miniconda3/envs/py38/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
        ForkingPickler(file, protocol).dump(obj)
    AttributeError: Can't pickle local object 'register.<locals>._handler'

### PR DESCRIPTION
**Pull request by ashleysommer**
Moves the subfunction _handler out to a module-level function, and parameterizes it with functools.partial().
Fixes the case when picking a sanic app which has a registered static route handler. This is usually encountered when attempting to use multiprocessing or auto_reload on OSX or Windows.
Fixes #1774

### CODE REVIEW

**Comment by Tronic** [comment]
This fixes static files but unfortunately there are also problems with route decorators:

```
# @app.get(...)
_pickle.PicklingError: Can't pickle <function my_handler at 0x10b2129d0>: it's not the same object as __main__.my_handler

# @app.websocket(...)
AttributeError: Can't pickle local object 'Sanic.websocket.<locals>.response.<locals>.websocket_handler'
```

**Comment by ashleysommer** [comment]
Ah, ok. I was testing on Linux and not seeing that problem. Thanks for the tip @Tronic

**Comment by ashleysommer** [comment]
This can probably be still merged, as it _does_ fix the static _handler pickle error, and adds a new test for that problem.
The route decorator pickle problem can probably be created as a secondary issue and receive an additional fix.

**Comment by ashleysommer** [comment]
I was hoping to get this change into the (belated) 20.03 release. Looks like it didn't make it. Still says one more review is required?

**Comment by ashleysommer** [comment]
Oh, when I saw the 20.3 PR go through yesterday, I thought we had done the 20.3 release. I'll merge this now and it might still make the release.

**Comment by ashleysommer** [comment]
@Tronic I've made a fix for the websocket_handler pickle error, I will open a PR with that shortly. However I still cannot reproduce the route decorator pickling error.
I've changed the mp context to 'spawn' as you suggested, and even force-picking the whole app with decorated routes, and cannot get it to fail with "Can't pickle <function handler at 0x0>: it's not the same object as __main__.handler" error.

Are you able to share some code which reproduces the pickling error with route decorators?

**Comment by ahopkins** [comment]
This can me merged?

**Comment by ashleysommer** [comment]
Yes, it's finished and approved and is ready to be merged.

**Pull request merged**
