### PR TITLE
Fix logo in config.py

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by vltr** [comment]
A broader question: will we still use this logo?

**Comment by hramezani** [comment]
@vltr I don't know. I just compare it with the logo in `README.rst` and saw an extra character on it.

**Comment by vltr** [comment]
@hramezani oh yes, that I noticed, sorry. I was just thinking out loud, let's see what other @huge-success/sanic-core-devs thinks of this (about having a logo in the `config.py` file).

**Comment by sjsadowski** [comment]
I'm not a fan of the logo in the config. First thing I had to figure out how to do was disable it so it wouldn't clutter my logs.

**Comment by abuckenheimer** [comment]
shoot I didn't mean to approve these, I think we actually need that extra backslash because it prevents a newline escape

**Comment by yunstanford** [comment]
gonna close this, and i agree we probably don't need this in config.py

**Pull request closed without merging**
