### PR TITLE
add drain method to StreamingHTTPResponse

### PR DESCRIPTION
**Pull request by adamhz**

### CODE REVIEW

**Comment by sjsadowski** [comment]
This is out of date and the PR author never responded to adding a test.

**Comment by vltr** [comment]
Yes, I think @ashleysommer already implemented this functionality (feel free to correct me)

**Comment by ashleysommer** [comment]
@vltr this PR might be actually something slightly different than the HTTP Drain functionality I added. I will have a look at it later today.

**Comment by vltr** [comment]
Thanks, @ashleysommer ! Reading the code again and the PR regarding the drain method (and other stuff) for release 0.8.0, I see this is a completely different issue. But, perhaps the idea behind this PR is still valid?

**Pull request closed without merging**
