### PR TITLE
Update stale.yml

### PR DESCRIPTION
**Pull request by ahopkins**
Add necessary label to ignore list

### CODE REVIEW

**Comment by andreymal** [comment]
Maybe "help wanted" should also be added?

**Comment by ahopkins** [comment]
Makes sense. Will do when I'm back at a computer.

**Comment by yunstanford** [comment]
@ahopkins are you going to add `help wanted` label as well ?

**Comment by ahopkins** [comment]
Yes. Tomorrow morning.

**Comment by yunstanford** [comment]
Added

**Pull request merged**
