### PR TITLE
Replaced str.format() method in core functionality

### PR DESCRIPTION
**Pull request by myuz**
That's the second part of functionality which replaces `str.format`() method to `f-strings`

Link on the first PR: https://github.com/huge-success/sanic/pull/1793

### CODE REVIEW

**Comment by mikeyusko** [comment]
@Tronic hey, thanks for the review, also one more thing, should I use `black my_file` in order to fix the problem? if yes, black will make a lot of syntax changes.

**Comment by Tronic** [comment]
`black --config ./.black.toml sanic/*.py`

**Comment by mikeyusko** [comment]
Thanks @Tronic, fixed.

**Comment by mikeyusko** [comment]
Done.

**Pull request merged**
