### PR TITLE
Improve FileNotFound exception

### PR DESCRIPTION
**Pull request by tomaszdrozdz**
@ahopkins @myusko 

Without this changes my web browser shows only
> File not found

With this changes it shows:
> File not found: path=./some/thing relative_url=/something

### CODE REVIEW

**Comment by ahopkins** [comment]
I think this might be an instance where it is better to leave it. If a message like that is desired, then there should probably be something to catch and reraise. We do not want to add something that could potentially leak information not intended.

**Comment by tomaszdrozdz** [comment]
OK.
How about another idea ?

**Comment by ahopkins** [comment]
```python
@app.exception(FileNotFound)
def handle_missing_files(request, exception):
    message = f"No file found at {exception.path=} looking at {exception.relative_url=}"
    return text(message, status=exception.status_code)
```

**Comment by tomaszdrozdz** [comment]
OK - You are right  - now I understand :)

---------

And now I understand i should have describe my issue more precisselly.

So i wanted to:

    app.static("/css", "./css", "css")

But going to web browser under: /css/main.css showed me only 
> File not found

There was also no any information what file, what path, ... in command line.

(My fault, I provided wrong directory path name).

So I just thought it would help me (and I think in such case it could also help other developers writing Sanic app) if i had more detailed information about what is not found in terminal (command line) where I run my Sanic app in debug mode.

Hope You understand my concern that in this case (and when running Sanic in debug mode) we could be more verbose and give more hint what is wrong.

**Comment by ahopkins** [comment]
Perhaps a `log.error` [here](https://github.com/huge-success/sanic/blob/master/sanic/static.py#L43) would help that.

**Pull request closed without merging**
