### PR TITLE
GIT1505: Backport changes from #1502 to 18.12LTS

### PR DESCRIPTION
**Pull request by harshanarayana**
Backport #1502 to 18.12LTS

### CODE REVIEW

**Comment by harshanarayana** [comment]
@huge-success/sanic-core-devs Ran into some odd UT failures on the Travis for this branch. had to bump up the `pytest` version. But after that, I am seeing some other failure as well. Especially with caplog assertions being done. Any Suggestions?

**Comment by sjsadowski** [comment]
Watching the build logs and it's definitely something with caplog sections. I originally was thinking they depended on the time prefetch, but it didn't happen when we merged to master for 19.3 so it will definitely require digging.

**Comment by harshanarayana** [comment]
@sjsadowski @ahopkins I will look into the failing Tests later today and fix them. I think a couple of them might need to be changed in terms of what they assert. Marking this as WIP until then.

**Comment by harshanarayana** [comment]
@ahopkins @sjsadowski I've fixed the UT for the breaking errors. I also fixed a few other warnings that were showing up in the UT and one of the flake test errors.

**Pull request merged**
