### PR TITLE
Fix imports and isort to remove from Makefile deprecated options

### PR DESCRIPTION
**Pull request by ahopkins**

### CODE REVIEW

**Comment by ahopkins** [comment]
on the tail of #1890

**Comment by ahopkins** [comment]
Linting is passing, but looks like it is complaining about `trio` annotations. :man_facepalming:

**Comment by ashleysommer** [comment]
I added back in the missing `#  type: ignore` hint after the `from trio import ...` line was split in `compat.py`, hope that fixes it.

**Comment by ashleysommer** [comment]
Yep, travis is passing now.

**Pull request merged**
