### PR TITLE
Upgrade websockets, resolve incompatible issue between multidict and websockets

### PR DESCRIPTION
**Pull request by yunstanford**
Fix: https://github.com/huge-success/sanic/issues/1629
Resolve incompatible issue between multidict and websockets.

### CODE REVIEW

**Comment by ahopkins** [comment]
Much needed. Thanks @yunstanford! Will look it over this weekend.

**Comment by yunstanford** [comment]
I'd like to schedule a release for this patch, can you guys take a look ? @ahopkins @seemethere

**Comment by snguyenthanh** [comment]
@yunstanford May I ask when this patch will get released ?

**Comment by ahopkins** [comment]
This was not something introduced by 19.6. So, this will likely  be a part of 19.9 released in September.

**Comment by blaisep** [comment]
Hi @Tronic , @ahopkins ,
When I tried to take over maintenance of the `python-sanic` in Fedora, I found that
Fedora packaging has blocked sanic because they require websockets >=8.0
( https://bugzilla.redhat.com/show_bug.cgi?id=1729908 )
 Should I go ahead and hack the dependency file to see if I can force the build?
  export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig"
or I am asking for trouble.
I don't want to cast `sanic` in a bad light by shoehorning it into the Fedora disto.

**Comment by ahopkins** [comment]
Upgrading the dependency is on my short list of things to do for an upcoming release.

**Pull request merged**
