### PR TITLE
Forgotten slot

### PR DESCRIPTION
**Pull request by eric-nieuwland**
Crashes the server at __init__() time

### CODE REVIEW

**Comment by eric-nieuwland** [comment]
macOS 10.15 Catalina
Created a fresh virtualenv with Python 3.8.
Existing code for a very basic single worker configuration worked fine with Python 3.7 and older Sanic.
Now wouldn't get passed
> app = Sanic("MyApp")
> app.static(...)  # for favicon
> app.add_route(root, "/")
> app.run(host="0.0.0.0", port=8000, debug=True)

Failed on app.run() with a complaint about non-existing attribute "_body_chunks" when creating a HttpProtocol instance when executing a serve() call in sanic/server.py

**Comment by johndiego** [comment]
same errors

**Comment by ahopkins** [comment]
@huge-success/sanic-release-managers

**Comment by sunshine2995** [comment]
> macOS 10.15 Catalina
> Created a fresh virtualenv with Python 3.8.
> Existing code for a very basic single worker configuration that worked fine with Python 3.7 and older Sanic.
> Now wouldn't get passed
> 
> > app = Sanic("MyApp")
> > app.static(...)  # for favicon
> > app.add_route(root, "/") # generates page from a template
> > app.run(host="0.0.0.0", port=8000, debug=True)
> 
> Failed on app.run() with a complaint about non-existing attribute "_body_chunks" when creating a HttpProtocol instance when executing a serve() call in sanic/server.py

same error

**Comment by rubik** [comment]
@ahopkins Who can push the release to PyPI? It's unfortunate that the most recent version is still completely broken.

**Comment by ahopkins** [comment]
@rubik If @sjsadowski  and @yunstanford do not take care of it today, then I will later this evening. With holidays and such I am sure everyone is busy.

In general, it is our practice that only the @huge-success/sanic-release-managers do this. But I can if need be as well.

**Comment by sjsadowski** [comment]
PyPI release is supposed to be automatically uploaded with the release, trying to identify what's broken in the travis build. We'll get it uploaded as soon as we can.

**Comment by ahopkins** [comment]
Version 19.12.2 is out with this change in place.

The broken Travis builds seem to be not related to the actual tests failing, but that each job seems to be trying to make the PyPI release. :thinking:

**Comment by rubik** [comment]
@ahopkins Great, thanks!

**Pull request merged**
