### PR TITLE
Delete asyncio_python37.rst

### PR DESCRIPTION
**Pull request by nitipit**
deprecate since there's an example at https://sanic.readthedocs.io/en/latest/sanic/examples.html

### CODE REVIEW

**Comment by ashleysommer** [comment]
@nitipit do you think we should remove documentation pages if there is a code snippet in the examples? I'm not sure I agree.

**Comment by nitipit** [comment]
@ashleysommer 
I think an example here which is more easier and more accurated to python 3.7 docs about how to use sanic with asyncio event loop.
https://sanic.readthedocs.io/en/latest/sanic/examples.html#logging-enhancements

However, that example point out different topics. I agree that just removing `asyncio_python37.rst` is not a good way to do.
So I think this pull request should be rejected.

**Comment by ahopkins** [comment]
I think this is probably something that ultimately will live in the new Sanic guide.

**Comment by ahopkins** [comment]
This was a mistaken reference. Ignore.

**Pull request closed without merging**
