### PR TITLE
No tracebacks on normal errors and prettier error pages

### PR DESCRIPTION
**Pull request by Tronic**
Refactored default exception handling and error pages.

- Tracebacks are logged for uncaught SanicExceptions now only if status=500 or quiet=False.
    * No traceback for 404 NotFound, 405 MethodNotAllowed, 503 ServiceUnavailable etc.
- Uncaught Internal Server Errors and other exceptions still cause a traceback to be logged.
- Override by exception object's flag quiet=True/False (if not defined or None, the above rules apply).
- New default error pages (errorpages.py):
    * Production mode used to be text/plain, now all responses are HTML5.
    * Now only logged (non-quiet) exceptions are shown, still only in debug mode.

### CODE REVIEW

**Comment by ashleysommer** [comment]
Oh, you beat me to it.
I just finished writing some code which does a very similar thing to fix #1766, I was about to open a PR.

My implementation took a different approach. It added the ability to flag each subclass of SanicException with a boolean whether or not to log the traceback. And by default the only one it sets to false for now is NotFound.

**Comment by Tronic** [comment]
Refactoring HTML formatting to a separate module, and traceback pages at least escape their strings before formatting into HTML. Ideally the traceback code would be entirely rewritten, possibly using https://github.com/tronic/niceback as basis. But this PR has already bloated way beyond its original purpose...

@huge-success/sanic-release-managers review?

**Comment by vltr** [comment]
Erm ... Can't we make use of the `DEBUG` flag to show (or not) these errors? I would like to see them in development but not in production mode ... But what to show on production? Keep the same behavior as original?

**Comment by Tronic** [comment]
It still doesn't make sense to print tracebacks for 404 or most other errors even if in debug mode because the only thing that traceback is going to show is Sanic router internals. But if you have a bug in your code and some unexpected exception flies out, you do get a traceback in log (even in production mode) and if in debug mode, also in browser.

**Comment by vltr** [comment]
> It still doesn't make sense to print tracebacks for 404 or most other errors even if in debug mode because the only thing that traceback is going to show is Sanic router internals.

Indeed.

> But if you have a bug in your code and some unexpected exception flies out, you do get a traceback in log (even in production mode) and if in debug mode, also in browser.

That makes sense to me.

If all these scenarios are covered, then I think it'll be a great addition. Just update the PR description (I really took a very quick look at the code and thought it was not taking `DEBUG` into consideration ... Anyway).

I really like your project for tracebacks and code errors, [niceback](https://github.com/tronic/niceback). I was also thinking that we (Sanic) lack some development-friendly tools ... Well, I plan on creating a topic on the forums about that soon :wink:

**Comment by Tronic** [comment]
@vltr Description updated.

**Pull request merged**
