### PR TITLE
Release v19.12.0

### PR DESCRIPTION
**Pull request by ahopkins**
Looks like there are a couple commits to bring over into `master`.

### CODE REVIEW

**Comment by sjsadowski** [comment]
Still having issues with the travis-ci/push build

**Comment by ahopkins** [comment]
Need me to look into anything? I'm not at a computer now, but I can be in a few hours.

**Comment by sjsadowski** [comment]
Not sure. The only failures are the pypi/rtd uploads. I'm back at work today so I'll need to look at this after hours.

**Comment by ahopkins** [comment]
It looks like **EACH** of the jobs is trying to submit to PyPI (hence the failures).

https://travis-ci.org/huge-success/sanic/builds/632042073

**Pull request merged**
