### PR TITLE
Enforce Datetime Type for Expires on Set-Cookie

### PR DESCRIPTION
**Pull request by LTMenezes**
Closes: #1453

### CODE REVIEW

**Comment by LTMenezes** [comment]
The CI appears to be failing for a reason outside this PR scope. It's a lint error on sanic/response.py.

Let me know if this is related to my PR or if you guys want me to fix it, I would be glad to help!

**Comment by vltr** [comment]
Thanks for your effort, @LTMenezes ! I guess this is something that was already been discussed, I just don't remember if there was any conclusions ... @harshanarayana , any thoughts?

**Comment by harshanarayana** [comment]
@vltr This is something we discussed in the forum. The conclusion was to let datetime be used as a valid value and raise an exception otherwise to inform that the type is invalid. (Enables easy date to string conversion in RFC Standard)

**Comment by harshanarayana** [comment]
@LTMenezes I looked at the travis jobs. 

```bash
would reformat /home/travis/build/huge-success/sanic/sanic/cookies.py
```

Looks like `black` detected a possible format change in the code for `cookies.py`. Can you just run the `make beautify` command once and commit the changes? That should fix the travis issues.

**Comment by LTMenezes** [comment]
Thanks for the review @harshanarayana! I applied the suggestions you made and fixed the build.

I also committed other files that the 'make beautify' command formatted, hope that this is okay.

**Comment by sjsadowski** [comment]
Looks ok to me too.

**Pull request merged**
