### PR TITLE
GIT-1591 Strict Slashes behavior fix

### PR DESCRIPTION
**Pull request by harshanarayana**
### TODO

- [x] Add documentation for the behavior change of `strict_slashes` attribute
- [x] Add example use cases with all possible combination of `strict_slashes` attribute
- [x] Fix linter issues in test and fix warnings for `test_client` usage

### CODE REVIEW

**Comment by ahopkins** [comment]
I am amending the title so that it is #1591 only. I think the dependency issue in #1592 is a quicker solve and needs a merge sooner than we will have this one resolved.

See #1595

**Comment by harshanarayana** [comment]
@ahopkins works for me.

**Comment by yunstanford** [comment]
What is the progress on this PR ? And are you targeting this on 19.6 ? @harshanarayana

**Comment by harshanarayana** [comment]
@yunstanford  Yes. I am going to follow the idea discussed in #1591 and split into two work items. Will fix the propagation of `strict_slashes` flag across. I will update the PR by end of the day.

**Comment by harshanarayana** [comment]
@huge-success/sanic-core-devs  I am good with this change from my end. Please take a look at the changes and see if there is any change required.

**Pull request merged**
