### PR TITLE
Return 206 when answering `Range` request

### PR DESCRIPTION
**Pull request by logannc**
Per RFC 7233, Sanic should return 206 when answering `Range` requests.

### CODE REVIEW

**Comment by logannc** [comment]
_May_ fix #603. Not sure since I don't know what is actually wrong in his use case.

**Comment by arnulfojr** [comment]
Can you please be more specific on what you aiming to solve with this PR?
As this only affects the response’s file_stream and stream functionality and not responding 206 to all requests that include the Range header

**Comment by logannc** [comment]
That's fair. I had a bit of tunnel vision because I was working on a file server so the only relevant response types for me were `file` and `file_stream`. 

Also, I am not really aware of a use for the Range header outside of file serving, nor would I know how to properly handle that generically, for all requests. `file` and `file_stream` are already 'Range aware' which makes it easy. For an arbitrary route, I could throw away stuff from the beginning and ends of the response to enforce Range and override the route's status code, but would that usually be what the developer would want? Certainly for a `stream` response or something, most implementations would be able to seek in a much more efficient way than reading and dropping from the front of the stream. Likewise, they can simply stop producing bytes instead of reading and dropping from the end of the stream. And overriding their status code, while RFC compliant, may not be what they want.

So, to be specific, I want to return 206 when serving up partial files due to a `Range` header, per the RFC. While the RFC may prescribe returning 206 in other scenarios (I can imagine partial content of data routes would be useful in some scenarios), there is not a clearly useful way to generically handle those, so my PR is only partially compliant and leaves the rest to the application developer.

**Comment by sjsadowski** [comment]
@logannc can you update your fork and resolve the conflicts there so that we can easily verify the merge with master?

**Comment by logannc** [comment]
Sorry, I'd meant to do this the next day but it slipped my mind.

> And overriding their status code, while RFC compliant, may not be what they want.

This is now relevant to the PR. Previously, the methods I changed didn't give the option to choose a status code so my overriding it was okay. I've updated the function signature so that the default is added later iff they don't specify a status code. It is less pretty, but it works.

**Comment by logannc** [comment]
It looks like these changes were incorporated in a different PR.

¯\\\_(ツ)_/¯

**Pull request closed without merging**
