### PR TITLE
Cherry pick PRs to backport to 19.12LTS

### PR DESCRIPTION
**Pull request by ashleysommer**
Includes fixes from:
https://github.com/huge-success/sanic/pull/1762
https://github.com/huge-success/sanic/pull/1764
https://github.com/huge-success/sanic/pull/1789

### CODE REVIEW

**Comment by ashleysommer** [comment]
Travis Type Checks are failing because 19.12LTS branch was never expected to have that level of type checking on it. The failures are not related to the commits in this PR.

**Comment by ahopkins** [comment]
@sjsadowski Let's try and circle back up on this early next week to get this built and pushed.

**Comment by ahopkins** [comment]
#1779?

**Comment by ashleysommer** [comment]
Oh, I didn't know #1779 exists. Though it looks like a rollup up a _lot_ more commits between end of December 2019 and February 2020. I'll comment in that PR.

**Comment by ashleysommer** [comment]
Double checking everything on this, tests look fine (just a couple of mypy fails in asgi.py unrelated to these changes).

**Comment by ahopkins** [comment]
@ashleysommer GitHub was complaining and would not let me push to your branch. So I created a new branch here and a new PR: #1900.

**Pull request closed without merging**
