### PR TITLE
Upgrade httpx

### PR DESCRIPTION
**Pull request by ahopkins**
I had thought pretty long about whether to get the PR for removing `httpx` requirement (#1850), but that didn't seem quite appropriate just yet.

Because `httpx` is a fairly fast moving project, there were a number of changes needed to be made to some tests as well as the test client. Hopefully, we will get `sanic-testing` completed and then we will not need to deal with these changes here.

### CODE REVIEW

**Review by ashleysommer — COMMENTED** [review]
Looks good to me

**Review by ashleysommer — DISMISSED** [review]

**Comment by ashleysommer** [comment]
ReuseableSanicTestClient and DelayableHTTPConnection are some pretty hairy hacks I put together a couple of years ago in order to test the HTTP Keep-Alive mechanism, and Request Timeouts respectively.
They're a pain to maintain, but I don't know of any other way to test these features (unless httpx gets these features natively).
It might be worth considering pulling these out of the sanic test code and into the Sanic-Testing project, to keep all of that stuff together.

**Comment by ashleysommer** [comment]
Black test failing:
```
would reformat /home/travis/build/huge-success/sanic/sanic/testing.py
would reformat /home/travis/build/huge-success/sanic/sanic/response.py
```

**Comment by ahopkins** [comment]
I agree. I have written and rewritten those several times because of the fast pace at which underlying libraries reorganize themselves. I do have a thought on how to handle, and this is actually THE reason I think we need to hold off on sanic-testing for now. 

While I understand the desire to move them out to keep them closer, I think the test themselves need to stay here because it is Sanic functionality we need to worry about. 

Therefore, I want to add the functionality into the core of sanic-testing so the tests can stay, but the hack clients can go.

**Comment by ahopkins** [comment]
Had to upgrade `black` and `isort` with the particular env I had running. Should be ready when done building.

**Review by ashleysommer — APPROVED** [review]

**Pull request merged**
